### ISSUE TITLE
example unable to run, cause cannot find icon

### ISSUE THREAD

**Issue by liaovq** [fluttercandies/flutter-interactive-chart#1]
```
IconButton(
  icon: Icon(_darkMode ? Icons.dark_mode : Icons.light_mode),
  onPressed: () => setState(() => _darkMode = !_darkMode),
),
```

The above code is in `example/lib/main.dart`, where **Icons.dark_mode** and **Icons.light_mode** will prompt an error:

> The getter 'dark_mode' isn't defined for the type 'Icons'.
Try importing the library that defines 'dark_mode', correcting the name to the name of an existing getter, or defining a getter or field named 'dark_mode'.

and I didn't find the corresponding icon in the following two sites either
- https://flutter.github.io/cupertino_icons/
- https://fonts.google.com/icons

version:
- flutter-interactive-chart: 0.2.0
- flutter: 2.2.3
- dart: 2.13.4

**Comment by h65wang** [comment]
It's part of the material icon font: https://fonts.google.com/icons?icon.query=dark+mode

**Comment by liaovq** [comment]
> Also, you can see the icon in the flutter framework source code; search for `dark_mode` in this file: https://raw.githubusercontent.com/flutter/flutter/master/packages/flutter/lib/src/material/icons.dart

Through this link, I realized that our flutter sdk has a different channel, and I also saw the added icon after switching from stable to master, thanks
