### ISSUE TITLE
Zoom in and out using a mouse wheel.

### ISSUE THREAD

**Issue by hongmono** [fluttercandies/flutter-interactive-chart#4]
How zoom in and out using a mouse wheel??

**Comment by hongmono** [comment]
in Windows

**Comment by hongmono** [comment]
in Web

**Comment by h65wang** [comment]
Thanks for pointing this out. This has been fixed in v0.3.1.

**Comment by hongmono** [comment]
> Thanks for pointing this out. This has been fixed in v0.3.1.

Thank you!
