### ISSUE TITLE
Custom Movie Averages

### ISSUE THREAD

**Issue by wedersonrsouza** [fluttercandies/flutter-interactive-chart#7]
I have a suggestion that could be a big difference and help users to customize chart indicators:

That in addition to the package itself calculate the moving average, it is also possible for the developer to include an object (dates and prices) already calculated, so he can customize the average with the values he deems necessary.

I, for example, need in addition to the OHLC that a line be plotted with the values I get from my API (a custom moving average).

**Comment by h65wang** [comment]
You can already do that, see [issue 3](https://github.com/fluttercandies/flutter-interactive-chart/issues/3).
